package com.mottc.chat.data.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mottc.chat.data.bean.ChatUser;
import com.mottc.chat.data.bean.ChatInviteMessage;

import com.mottc.chat.data.local.ChatUserDao;
import com.mottc.chat.data.local.ChatInviteMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatUserDaoConfig;
    private final DaoConfig chatInviteMessageDaoConfig;

    private final ChatUserDao chatUserDao;
    private final ChatInviteMessageDao chatInviteMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatUserDaoConfig = daoConfigMap.get(ChatUserDao.class).clone();
        chatUserDaoConfig.initIdentityScope(type);

        chatInviteMessageDaoConfig = daoConfigMap.get(ChatInviteMessageDao.class).clone();
        chatInviteMessageDaoConfig.initIdentityScope(type);

        chatUserDao = new ChatUserDao(chatUserDaoConfig, this);
        chatInviteMessageDao = new ChatInviteMessageDao(chatInviteMessageDaoConfig, this);

        registerDao(ChatUser.class, chatUserDao);
        registerDao(ChatInviteMessage.class, chatInviteMessageDao);
    }
    
    public void clear() {
        chatUserDaoConfig.clearIdentityScope();
        chatInviteMessageDaoConfig.clearIdentityScope();
    }

    public ChatUserDao getChatUserDao() {
        return chatUserDao;
    }

    public ChatInviteMessageDao getChatInviteMessageDao() {
        return chatInviteMessageDao;
    }

}
